/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AtivosRouteImport } from './routes/ativos'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CompliancePoliticasRouteImport } from './routes/compliance-politicas'
import { Route as ConfiguracoesServicosLeadsRouteImport } from './routes/configuracoes-servicos-leads'
import { Route as ConfiguracoesTemplatesContratosRouteImport } from './routes/configuracoes-templates-contratos'
import { Route as ConfiguracoesVariaveisContratosRouteImport } from './routes/configuracoes-variaveis-contratos'
import { Route as ContabilidadeRouteImport } from './routes/contabilidade'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EstruturaRouteImport } from './routes/estrutura'
import { Route as EstruturaOrganizacionalRouteImport } from './routes/estrutura-organizacional'
import { Route as EstruturaSocietariaRouteImport } from './routes/estrutura-societaria'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as NotaFiscalRouteImport } from './routes/nota-fiscal'
import { Route as ParticipacoesRouteImport } from './routes/participacoes'
import { Route as PatrimonioLicencasRouteImport } from './routes/patrimonio-licencas'
import { Route as PropriedadeIntelectualRouteImport } from './routes/propriedade-intelectual'
import { Route as RateioRouteImport } from './routes/rateio'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RepassesRouteImport } from './routes/repasses'
import { Route as RhRouteImport } from './routes/rh'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as ConfiguracoesIntegracoesRouteImport } from './routes/configuracoes/integracoes'
import { Route as UnidadesUnitIdRouteImport } from './routes/unidades.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosRoute = AtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompliancePoliticasRoute = CompliancePoliticasRouteImport.update({
  id: '/compliance-politicas',
  path: '/compliance-politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesServicosLeadsRoute =
  ConfiguracoesServicosLeadsRouteImport.update({
    id: '/configuracoes-servicos-leads',
    path: '/configuracoes-servicos-leads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesTemplatesContratosRoute =
  ConfiguracoesTemplatesContratosRouteImport.update({
    id: '/configuracoes-templates-contratos',
    path: '/configuracoes-templates-contratos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesVariaveisContratosRoute =
  ConfiguracoesVariaveisContratosRouteImport.update({
    id: '/configuracoes-variaveis-contratos',
    path: '/configuracoes-variaveis-contratos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContabilidadeRoute = ContabilidadeRouteImport.update({
  id: '/contabilidade',
  path: '/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaRoute = EstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaOrganizacionalRoute = EstruturaOrganizacionalRouteImport.update({
  id: '/estrutura-organizacional',
  path: '/estrutura-organizacional',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaSocietariaRoute = EstruturaSocietariaRouteImport.update({
  id: '/estrutura-societaria',
  path: '/estrutura-societaria',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const NotaFiscalRoute = NotaFiscalRouteImport.update({
  id: '/nota-fiscal',
  path: '/nota-fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipacoesRoute = ParticipacoesRouteImport.update({
  id: '/participacoes',
  path: '/participacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioLicencasRoute = PatrimonioLicencasRouteImport.update({
  id: '/patrimonio-licencas',
  path: '/patrimonio-licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const PropriedadeIntelectualRoute = PropriedadeIntelectualRouteImport.update({
  id: '/propriedade-intelectual',
  path: '/propriedade-intelectual',
  getParentRoute: () => rootRouteImport,
} as any)
const RateioRoute = RateioRouteImport.update({
  id: '/rateio',
  path: '/rateio',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RepassesRoute = RepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIntegracoesRoute =
  ConfiguracoesIntegracoesRouteImport.update({
    id: '/configuracoes/integracoes',
    path: '/configuracoes/integracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnidadesUnitIdRoute = UnidadesUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => UnidadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/ativos': typeof AtivosRoute
  '/auditoria': typeof AuditoriaRoute
  '/clientes': typeof ClientesRoute
  '/compliance-politicas': typeof CompliancePoliticasRoute
  '/configuracoes-servicos-leads': typeof ConfiguracoesServicosLeadsRoute
  '/configuracoes-templates-contratos': typeof ConfiguracoesTemplatesContratosRoute
  '/configuracoes-variaveis-contratos': typeof ConfiguracoesVariaveisContratosRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/estrutura': typeof EstruturaRoute
  '/estrutura-organizacional': typeof EstruturaOrganizacionalRoute
  '/estrutura-societaria': typeof EstruturaSocietariaRoute
  '/integracoes': typeof IntegracoesRoute
  '/juridico': typeof JuridicoRoute
  '/nota-fiscal': typeof NotaFiscalRoute
  '/participacoes': typeof ParticipacoesRoute
  '/patrimonio-licencas': typeof PatrimonioLicencasRoute
  '/propriedade-intelectual': typeof PropriedadeIntelectualRoute
  '/rateio': typeof RateioRoute
  '/relatorios': typeof RelatoriosRoute
  '/repasses': typeof RepassesRoute
  '/rh': typeof RhRoute
  '/transacoes': typeof TransacoesRoute
  '/unidades': typeof UnidadesRouteWithChildren
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/unidades/$unitId': typeof UnidadesUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/ativos': typeof AtivosRoute
  '/auditoria': typeof AuditoriaRoute
  '/clientes': typeof ClientesRoute
  '/compliance-politicas': typeof CompliancePoliticasRoute
  '/configuracoes-servicos-leads': typeof ConfiguracoesServicosLeadsRoute
  '/configuracoes-templates-contratos': typeof ConfiguracoesTemplatesContratosRoute
  '/configuracoes-variaveis-contratos': typeof ConfiguracoesVariaveisContratosRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/estrutura': typeof EstruturaRoute
  '/estrutura-organizacional': typeof EstruturaOrganizacionalRoute
  '/estrutura-societaria': typeof EstruturaSocietariaRoute
  '/integracoes': typeof IntegracoesRoute
  '/juridico': typeof JuridicoRoute
  '/nota-fiscal': typeof NotaFiscalRoute
  '/participacoes': typeof ParticipacoesRoute
  '/patrimonio-licencas': typeof PatrimonioLicencasRoute
  '/propriedade-intelectual': typeof PropriedadeIntelectualRoute
  '/rateio': typeof RateioRoute
  '/relatorios': typeof RelatoriosRoute
  '/repasses': typeof RepassesRoute
  '/rh': typeof RhRoute
  '/transacoes': typeof TransacoesRoute
  '/unidades': typeof UnidadesRouteWithChildren
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/unidades/$unitId': typeof UnidadesUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/ativos': typeof AtivosRoute
  '/auditoria': typeof AuditoriaRoute
  '/clientes': typeof ClientesRoute
  '/compliance-politicas': typeof CompliancePoliticasRoute
  '/configuracoes-servicos-leads': typeof ConfiguracoesServicosLeadsRoute
  '/configuracoes-templates-contratos': typeof ConfiguracoesTemplatesContratosRoute
  '/configuracoes-variaveis-contratos': typeof ConfiguracoesVariaveisContratosRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/estrutura': typeof EstruturaRoute
  '/estrutura-organizacional': typeof EstruturaOrganizacionalRoute
  '/estrutura-societaria': typeof EstruturaSocietariaRoute
  '/integracoes': typeof IntegracoesRoute
  '/juridico': typeof JuridicoRoute
  '/nota-fiscal': typeof NotaFiscalRoute
  '/participacoes': typeof ParticipacoesRoute
  '/patrimonio-licencas': typeof PatrimonioLicencasRoute
  '/propriedade-intelectual': typeof PropriedadeIntelectualRoute
  '/rateio': typeof RateioRoute
  '/relatorios': typeof RelatoriosRoute
  '/repasses': typeof RepassesRoute
  '/rh': typeof RhRoute
  '/transacoes': typeof TransacoesRoute
  '/unidades': typeof UnidadesRouteWithChildren
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/unidades/$unitId': typeof UnidadesUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/agenda'
    | '/atendimento'
    | '/ativos'
    | '/auditoria'
    | '/clientes'
    | '/compliance-politicas'
    | '/configuracoes-servicos-leads'
    | '/configuracoes-templates-contratos'
    | '/configuracoes-variaveis-contratos'
    | '/contabilidade'
    | '/contratos'
    | '/crm'
    | '/estrutura'
    | '/estrutura-organizacional'
    | '/estrutura-societaria'
    | '/integracoes'
    | '/juridico'
    | '/nota-fiscal'
    | '/participacoes'
    | '/patrimonio-licencas'
    | '/propriedade-intelectual'
    | '/rateio'
    | '/relatorios'
    | '/repasses'
    | '/rh'
    | '/transacoes'
    | '/unidades'
    | '/configuracoes/integracoes'
    | '/unidades/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/agenda'
    | '/atendimento'
    | '/ativos'
    | '/auditoria'
    | '/clientes'
    | '/compliance-politicas'
    | '/configuracoes-servicos-leads'
    | '/configuracoes-templates-contratos'
    | '/configuracoes-variaveis-contratos'
    | '/contabilidade'
    | '/contratos'
    | '/crm'
    | '/estrutura'
    | '/estrutura-organizacional'
    | '/estrutura-societaria'
    | '/integracoes'
    | '/juridico'
    | '/nota-fiscal'
    | '/participacoes'
    | '/patrimonio-licencas'
    | '/propriedade-intelectual'
    | '/rateio'
    | '/relatorios'
    | '/repasses'
    | '/rh'
    | '/transacoes'
    | '/unidades'
    | '/configuracoes/integracoes'
    | '/unidades/$unitId'
  id:
    | '__root__'
    | '/'
    | '/acessos'
    | '/agenda'
    | '/atendimento'
    | '/ativos'
    | '/auditoria'
    | '/clientes'
    | '/compliance-politicas'
    | '/configuracoes-servicos-leads'
    | '/configuracoes-templates-contratos'
    | '/configuracoes-variaveis-contratos'
    | '/contabilidade'
    | '/contratos'
    | '/crm'
    | '/estrutura'
    | '/estrutura-organizacional'
    | '/estrutura-societaria'
    | '/integracoes'
    | '/juridico'
    | '/nota-fiscal'
    | '/participacoes'
    | '/patrimonio-licencas'
    | '/propriedade-intelectual'
    | '/rateio'
    | '/relatorios'
    | '/repasses'
    | '/rh'
    | '/transacoes'
    | '/unidades'
    | '/configuracoes/integracoes'
    | '/unidades/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessosRoute: typeof AcessosRoute
  AgendaRoute: typeof AgendaRoute
  AtendimentoRoute: typeof AtendimentoRoute
  AtivosRoute: typeof AtivosRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ClientesRoute: typeof ClientesRoute
  CompliancePoliticasRoute: typeof CompliancePoliticasRoute
  ConfiguracoesServicosLeadsRoute: typeof ConfiguracoesServicosLeadsRoute
  ConfiguracoesTemplatesContratosRoute: typeof ConfiguracoesTemplatesContratosRoute
  ConfiguracoesVariaveisContratosRoute: typeof ConfiguracoesVariaveisContratosRoute
  ContabilidadeRoute: typeof ContabilidadeRoute
  ContratosRoute: typeof ContratosRoute
  CrmRoute: typeof CrmRoute
  EstruturaRoute: typeof EstruturaRoute
  EstruturaOrganizacionalRoute: typeof EstruturaOrganizacionalRoute
  EstruturaSocietariaRoute: typeof EstruturaSocietariaRoute
  IntegracoesRoute: typeof IntegracoesRoute
  JuridicoRoute: typeof JuridicoRoute
  NotaFiscalRoute: typeof NotaFiscalRoute
  ParticipacoesRoute: typeof ParticipacoesRoute
  PatrimonioLicencasRoute: typeof PatrimonioLicencasRoute
  PropriedadeIntelectualRoute: typeof PropriedadeIntelectualRoute
  RateioRoute: typeof RateioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RepassesRoute: typeof RepassesRoute
  RhRoute: typeof RhRoute
  TransacoesRoute: typeof TransacoesRoute
  UnidadesRoute: typeof UnidadesRouteWithChildren
  ConfiguracoesIntegracoesRoute: typeof ConfiguracoesIntegracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos': {
      id: '/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-politicas': {
      id: '/compliance-politicas'
      path: '/compliance-politicas'
      fullPath: '/compliance-politicas'
      preLoaderRoute: typeof CompliancePoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-servicos-leads': {
      id: '/configuracoes-servicos-leads'
      path: '/configuracoes-servicos-leads'
      fullPath: '/configuracoes-servicos-leads'
      preLoaderRoute: typeof ConfiguracoesServicosLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-templates-contratos': {
      id: '/configuracoes-templates-contratos'
      path: '/configuracoes-templates-contratos'
      fullPath: '/configuracoes-templates-contratos'
      preLoaderRoute: typeof ConfiguracoesTemplatesContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-variaveis-contratos': {
      id: '/configuracoes-variaveis-contratos'
      path: '/configuracoes-variaveis-contratos'
      fullPath: '/configuracoes-variaveis-contratos'
      preLoaderRoute: typeof ConfiguracoesVariaveisContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidade': {
      id: '/contabilidade'
      path: '/contabilidade'
      fullPath: '/contabilidade'
      preLoaderRoute: typeof ContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura': {
      id: '/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof EstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura-organizacional': {
      id: '/estrutura-organizacional'
      path: '/estrutura-organizacional'
      fullPath: '/estrutura-organizacional'
      preLoaderRoute: typeof EstruturaOrganizacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura-societaria': {
      id: '/estrutura-societaria'
      path: '/estrutura-societaria'
      fullPath: '/estrutura-societaria'
      preLoaderRoute: typeof EstruturaSocietariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nota-fiscal': {
      id: '/nota-fiscal'
      path: '/nota-fiscal'
      fullPath: '/nota-fiscal'
      preLoaderRoute: typeof NotaFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participacoes': {
      id: '/participacoes'
      path: '/participacoes'
      fullPath: '/participacoes'
      preLoaderRoute: typeof ParticipacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio-licencas': {
      id: '/patrimonio-licencas'
      path: '/patrimonio-licencas'
      fullPath: '/patrimonio-licencas'
      preLoaderRoute: typeof PatrimonioLicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propriedade-intelectual': {
      id: '/propriedade-intelectual'
      path: '/propriedade-intelectual'
      fullPath: '/propriedade-intelectual'
      preLoaderRoute: typeof PropriedadeIntelectualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rateio': {
      id: '/rateio'
      path: '/rateio'
      fullPath: '/rateio'
      preLoaderRoute: typeof RateioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repasses': {
      id: '/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof RepassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/integracoes': {
      id: '/configuracoes/integracoes'
      path: '/configuracoes/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof ConfiguracoesIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades/$unitId': {
      id: '/unidades/$unitId'
      path: '/$unitId'
      fullPath: '/unidades/$unitId'
      preLoaderRoute: typeof UnidadesUnitIdRouteImport
      parentRoute: typeof UnidadesRoute
    }
  }
}

interface UnidadesRouteChildren {
  UnidadesUnitIdRoute: typeof UnidadesUnitIdRoute
}

const UnidadesRouteChildren: UnidadesRouteChildren = {
  UnidadesUnitIdRoute: UnidadesUnitIdRoute,
}

const UnidadesRouteWithChildren = UnidadesRoute._addFileChildren(
  UnidadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessosRoute: AcessosRoute,
  AgendaRoute: AgendaRoute,
  AtendimentoRoute: AtendimentoRoute,
  AtivosRoute: AtivosRoute,
  AuditoriaRoute: AuditoriaRoute,
  ClientesRoute: ClientesRoute,
  CompliancePoliticasRoute: CompliancePoliticasRoute,
  ConfiguracoesServicosLeadsRoute: ConfiguracoesServicosLeadsRoute,
  ConfiguracoesTemplatesContratosRoute: ConfiguracoesTemplatesContratosRoute,
  ConfiguracoesVariaveisContratosRoute: ConfiguracoesVariaveisContratosRoute,
  ContabilidadeRoute: ContabilidadeRoute,
  ContratosRoute: ContratosRoute,
  CrmRoute: CrmRoute,
  EstruturaRoute: EstruturaRoute,
  EstruturaOrganizacionalRoute: EstruturaOrganizacionalRoute,
  EstruturaSocietariaRoute: EstruturaSocietariaRoute,
  IntegracoesRoute: IntegracoesRoute,
  JuridicoRoute: JuridicoRoute,
  NotaFiscalRoute: NotaFiscalRoute,
  ParticipacoesRoute: ParticipacoesRoute,
  PatrimonioLicencasRoute: PatrimonioLicencasRoute,
  PropriedadeIntelectualRoute: PropriedadeIntelectualRoute,
  RateioRoute: RateioRoute,
  RelatoriosRoute: RelatoriosRoute,
  RepassesRoute: RepassesRoute,
  RhRoute: RhRoute,
  TransacoesRoute: TransacoesRoute,
  UnidadesRoute: UnidadesRouteWithChildren,
  ConfiguracoesIntegracoesRoute: ConfiguracoesIntegracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
