import { useMemo, useState } from "react";
import { useRouterState } from "@tanstack/react-router";
import { Download, Eye, Filter, MoreHorizontal, Pencil, Plus, Search, SlidersHorizontal, Trash2 } from "lucide-react";

import { Button } from "@/shared/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/shared/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/shared/components/ui/dropdown-menu";
import { Input } from "@/shared/components/ui/input";
import { Label } from "@/shared/components/ui/label";
import { StatusPill } from "@/shared/components/ui-kit";

type Kpi = { label: string; value: string; hint?: string };
type PageDefinition = { eyebrow: string; title: string; description: string; tabs?: string[]; columns: string[]; rows: string[][]; primaryAction: string; kpis: Kpi[]; summary: string[] };
type EditorState = { mode: "view" | "edit" | "create"; index?: number; row?: string[] } | null;

const commonKpis = (total: string): Kpi[] => [
  { label: "Registros", value: total, hint: "Visão atual" },
  { label: "Ativos", value: total, hint: "Operação corrente" },
  { label: "Pendências", value: "2", hint: "Requer atenção" },
  { label: "Atualizado", value: "Hoje", hint: "Frontend demonstrativo" },
];

const page = (eyebrow: string, title: string, description: string, columns: string[], rows: string[][], primaryAction: string, tabs?: string[], kpis?: Kpi[], summary?: string[]): PageDefinition => ({
  eyebrow, title, description, columns, rows, primaryAction, tabs,
  kpis: kpis ?? commonKpis(String(rows.length)),
  summary: summary ?? ["Cadastros organizados por escopo e unidade.", "Ações de visualizar, editar e arquivar disponíveis.", "Busca, filtros, exportação e exibição disponíveis no frontend."],
});

const PAGES: Record<string, PageDefinition> = {
  "/": page("VISÃO EXECUTIVA", "Dashboard", "Visão consolidada da operação, faturamento, custos, resultado distribuível e repasses da Lander Solutions.", ["Unidade", "Receita", "Custos", "Resultado", "Margem", "Status"], [["Music OS 360", "R$ 82.400", "R$ 28.100", "R$ 54.300", "65,9%", "Saudável"], ["Vivendo da Música", "R$ 61.780", "R$ 22.430", "R$ 39.350", "63,7%", "Saudável"], ["Corporativo", "R$ 40.740", "R$ 20.950", "R$ 19.790", "48,6%", "Atenção"]], "Abrir relatório gerencial", ["Visão geral", "Financeiro", "Unidades", "Obrigações"], [{ label: "Faturamento bruto", value: "R$ 184.920", hint: "+12,4% no mês" }, { label: "Custos e impostos", value: "R$ 71.480", hint: "38,7% do faturamento" }, { label: "Resultado distribuível", value: "R$ 113.440", hint: "61,3% de margem" }, { label: "Repasses pendentes", value: "R$ 28.360", hint: "3 obrigações" }], ["Receita recorrente: R$ 94.870.", "Caixa disponível: R$ 126.740.", "3 repasses pendentes e 2 contratos próximos do vencimento."]),
  "/agenda": page("OPERAÇÕES", "Agenda corporativa", "Compromissos, prazos, reuniões e eventos operacionais.", ["Compromisso", "Data", "Responsável", "Vínculo", "Status"], [["Reunião financeira", "18/08/2026 09:00", "Deyvisson", "Corporativo", "Confirmado"], ["Revisão de contrato", "19/08/2026 14:00", "Jurídico", "Music OS 360", "Pendente"], ["Fechamento mensal", "31/08/2026 17:00", "Financeiro", "Corporativo", "Planejado"], ["Revisão de produto", "21/08/2026 10:30", "Produto", "Vivendo da Música", "Confirmado"]], "Novo compromisso", ["Agenda", "Prazos", "Reuniões"]),
  "/estrutura-organizacional": page("EMPRESA", "Cadastros da Empresa", "Entidades, departamentos, cargos, produtos, serviços, projetos e centros financeiros.", ["Código", "Cadastro", "Tipo", "Vínculo", "Status"], [["SRV-001", "Desenvolvimento de software", "Serviço", "Corporativo", "Ativo"], ["PRD-001", "Music OS 360", "Produto", "Music OS 360", "Ativo"], ["PRD-002", "Vivendo da Música", "Produto", "Vivendo da Música", "Ativo"], ["DEP-001", "Financeiro", "Departamento", "Corporativo", "Ativo"], ["DEP-002", "Tecnologia", "Departamento", "Corporativo", "Ativo"]], "Novo registro", ["Serviços", "Produtos", "Entidades", "Departamentos", "Cargos", "Projetos", "Centros"]),
  "/estrutura": page("EMPRESA", "Estrutura Corporativa", "Mapa operacional das entidades, unidades e estruturas que sustentam a Lander Solutions.", ["Elemento", "Categoria", "Responsável", "Situação"], [["Lander Solutions Ltda.", "Entidade jurídica", "Diretoria", "Ativo"], ["Music OS 360", "Unidade de negócio", "Produto", "Ativo"], ["Vivendo da Música", "Unidade de negócio", "Produto", "Ativo"], ["Financeiro", "Departamento", "Diretoria", "Ativo"]], "Novo elemento"),
  "/estrutura-societaria": page("EMPRESA", "Estrutura Societária", "Capital social, sócios, quotas e composição societária da entidade jurídica.", ["Sócio", "Documento", "Participação", "Capital", "Status"], [["Sócio administrador", "***.***.***-**", "60%", "R$ 60.000", "Ativo"], ["Sócio investidor", "***.***.***-**", "40%", "R$ 40.000", "Ativo"]], "Novo sócio", ["Sócios", "Capital", "Alterações"], [{ label: "Capital social", value: "R$ 100.000" }, { label: "Sócios ativos", value: "2" }, { label: "Quotas", value: "100.000" }, { label: "Integralizado", value: "100%" }]),
  "/unidades": page("OPERAÇÕES", "Produtos / Unidades", "Centros econômicos com acompanhamento próprio de receita, custos e resultado.", ["Unidade", "Tipo", "Receita", "Resultado", "Margem", "Status"], [["Music OS 360", "SaaS", "R$ 82.400", "R$ 54.300", "65,9%", "Ativo"], ["Vivendo da Música", "Produto digital", "R$ 61.780", "R$ 39.350", "63,7%", "Ativo"], ["Corporativo", "Centro corporativo", "R$ 40.740", "R$ 19.790", "48,6%", "Ativo"]], "Nova unidade", ["Unidades", "Produtos", "Serviços", "Projetos"]),
  "/ativos": page("EMPRESA", "Ativos corporativos", "Equipamentos, softwares, domínios e ativos intangíveis.", ["Ativo", "Categoria", "Responsável", "Valor", "Status"], [["Notebook Dell 01", "Equipamento", "Tecnologia", "R$ 7.900", "Em uso"], ["lander.solutions", "Domínio", "Tecnologia", "R$ 180/ano", "Ativo"], ["Figma Professional", "Software", "Design", "R$ 920/mês", "Ativo"], ["Certificado digital A1", "Certificado", "Fiscal", "R$ 260/ano", "Ativo"]], "Novo ativo", ["Todos", "Equipamentos", "Softwares", "Domínios", "Intangíveis"]),
  "/patrimonio-licencas": page("EMPRESA", "Patrimônio e Licenças", "Controle de patrimônio, custódia, garantias e licenças administrativas.", ["Item", "Patrimônio", "Custódia", "Renovação", "Status"], [["MacBook Pro M4", "PAT-0021", "Design", "—", "Em uso"], ["Microsoft 365", "LIC-0008", "Corporativo", "12/11/2026", "Ativo"], ["Certificado A1", "LIC-0012", "Fiscal", "08/01/2027", "Ativo"], ["Adobe Creative Cloud", "LIC-0015", "Design", "24/09/2026", "Ativo"]], "Novo patrimônio", ["Patrimônio", "Licenças", "Custódia", "Renovações"]),
  "/contratos": page("CONTRATOS", "Contratos", "Instrumentos celebrados pela Lander Solutions e vinculados a clientes, produtos, serviços e unidades.", ["Contrato", "Cliente", "Objeto", "Valor", "Vigência", "Status"], [["CTR-2026-041", "Orbita Comércio Ltda.", "Desenvolvimento SaaS", "R$ 48.000", "01/08–31/01", "Ativo"], ["CTR-2026-039", "Nexo Produções", "Licença Music OS 360", "R$ 2.490/mês", "15/07–14/07", "Ativo"], ["CTR-2026-032", "Aurora Digital", "Consultoria", "R$ 18.500", "10/06–10/09", "Ativo"], ["CTR-2026-028", "Estúdio Horizonte", "Distribuição", "R$ 9.800", "01/05–31/10", "Renovação"]], "Criar contrato", ["Todos", "Ativos", "Rascunhos", "Assinaturas", "Renovações"]),
  "/transacoes": page("FINANCEIRO", "Transações", "Receitas e despesas conciliadas por unidade, conta, centro e competência.", ["Data", "Descrição", "Tipo", "Unidade", "Conta", "Valor", "Status"], [["16/08/2026", "Recebimento CTR-041", "Receita", "Corporativo", "Itaú", "+ R$ 12.000", "Conciliada"], ["16/08/2026", "AWS Cloud", "Despesa", "Music OS 360", "Inter", "- R$ 4.820", "Conciliada"], ["15/08/2026", "Stripe", "Taxa financeira", "Vivendo da Música", "Stripe", "- R$ 1.760", "Conciliada"], ["15/08/2026", "Google Workspace", "Despesa", "Corporativo", "Inter", "- R$ 860", "Ratear"]], "Nova transação", ["Todas", "Receitas", "Despesas", "Não conciliadas", "Importações"], [{ label: "Entradas", value: "R$ 184.920" }, { label: "Saídas", value: "R$ 71.480" }, { label: "Saldo líquido", value: "R$ 113.440" }, { label: "Não conciliadas", value: "6" }]),
  "/contabilidade": page("FINANCEIRO", "Contabilidade", "Demonstração gerencial por competência com receitas, custos e resultado.", ["Conta", "Categoria", "Débito", "Crédito", "Saldo"], [["Receita de serviços", "Receita", "R$ 0", "R$ 122.180", "R$ 122.180 C"], ["Receita SaaS", "Receita", "R$ 0", "R$ 62.740", "R$ 62.740 C"], ["Infraestrutura", "Despesa", "R$ 31.400", "R$ 0", "R$ 31.400 D"], ["Impostos", "Despesa", "R$ 18.930", "R$ 0", "R$ 18.930 D"]], "Novo lançamento", ["DRE", "Razão", "Balancete", "Plano de contas"]),
  "/nota-fiscal": page("FISCAL", "Notas Fiscais", "Emissão e controle de documentos fiscais de entrada e saída.", ["Número", "Tipo", "Cliente / Fornecedor", "Emissão", "Valor", "Status"], [["NFS-e 000184", "Saída", "Orbita Comércio Ltda.", "16/08/2026", "R$ 12.000", "Emitida"], ["NFS-e 000183", "Saída", "Nexo Produções", "15/08/2026", "R$ 2.490", "Emitida"], ["NF-e 438219", "Entrada", "Dell Brasil", "12/08/2026", "R$ 7.900", "Recebida"], ["NFS-e 000182", "Saída", "Aurora Digital", "10/08/2026", "R$ 6.166", "Emitida"]], "Registrar nota", ["Todas", "Saída", "Entrada", "Pendências"]),
  "/rateio": page("CUSTOS & RATEIOS", "Rateio de Custos", "Distribuição de despesas compartilhadas entre produtos, projetos e corporativo.", ["Competência", "Despesa", "Critério", "Origem", "Destinos", "Status"], [["08/2026", "Google Workspace", "Usuários ativos", "Corporativo", "3 unidades", "Calculado"], ["08/2026", "Contabilidade", "Receita proporcional", "Corporativo", "3 unidades", "Aprovado"], ["08/2026", "AWS compartilhada", "Uso/consumo", "Tecnologia", "2 unidades", "Pendente"], ["08/2026", "Figma", "Usuários ativos", "Design", "2 unidades", "Calculado"]], "Novo rateio", ["Rateios", "Regras", "Memórias", "Aprovações"]),
  "/participacoes": page("PARTICIPAÇÕES & REPASSES", "Participações", "Regras de participação econômica aplicadas ao resultado distribuível.", ["Beneficiário", "Unidade", "Base", "Percentual", "Vigência", "Status"], [["Sócio A", "Music OS 360", "Resultado líquido", "35%", "01/01/2026", "Ativo"], ["Sócio B", "Music OS 360", "Resultado líquido", "15%", "01/01/2026", "Ativo"], ["Sócio A", "Vivendo da Música", "Resultado líquido", "40%", "01/03/2026", "Ativo"]], "Nova participação", ["Participações", "Apurações", "Memórias"]),
  "/repasses": page("PARTICIPAÇÕES & REPASSES", "Repasses", "Obrigações de pagamento derivadas das participações aprovadas.", ["Beneficiário", "Competência", "Unidade", "Valor devido", "Pago", "Saldo", "Status"], [["Sócio A", "08/2026", "Music OS 360", "R$ 19.005", "R$ 9.500", "R$ 9.505", "Parcial"], ["Sócio B", "08/2026", "Music OS 360", "R$ 8.145", "R$ 8.145", "R$ 0", "Pago"], ["Sócio A", "08/2026", "Vivendo da Música", "R$ 15.740", "R$ 0", "R$ 15.740", "Pendente"]], "Registrar repasse", ["Obrigações", "Pagamentos", "Conciliação"]),
  "/atendimento": page("ATENDIMENTO", "Atendimento e Suporte", "Filas, tickets, conversas e SLAs dos clientes e produtos.", ["Ticket", "Cliente", "Assunto", "Produto", "SLA", "Status"], [["SUP-1048", "Nexo Produções", "Acesso ao painel", "Music OS 360", "1h 12m", "Em atendimento"], ["SUP-1047", "Aurora Digital", "Dúvida contratual", "Corporativo", "3h 20m", "Aberto"], ["SUP-1046", "Orbita Comércio", "Integração API", "Projeto SaaS", "Resolvido", "Fechado"], ["SUP-1045", "Estúdio Horizonte", "Distribuição", "Music OS 360", "42m", "Em atendimento"]], "Novo ticket", ["Caixa de entrada", "Tickets", "SLA", "Automações"]),
  "/rh": page("GESTÃO CORPORATIVA", "Recursos Humanos", "Colaboradores, vínculos, documentos, equipamentos e rotinas administrativas.", ["Colaborador", "Cargo", "Departamento", "Admissão", "Vínculo", "Status"], [["Marina Costa", "Analista Financeiro", "Financeiro", "04/03/2025", "CLT", "Ativo"], ["Rafael Lima", "Desenvolvedor", "Tecnologia", "12/08/2024", "PJ", "Ativo"], ["Camila Souza", "Designer", "Produto", "18/02/2026", "PJ", "Ativo"], ["João Ribeiro", "Analista Comercial", "Comercial", "08/06/2026", "CLT", "Ativo"]], "Novo colaborador", ["Pessoas", "Vínculos", "Documentos", "Ausências", "Equipamentos", "Onboarding"]),
  "/juridico": page("GOVERNANÇA", "Jurídico", "Assuntos jurídicos, processos, riscos, eventos e prazos.", ["Caso", "Tipo", "Responsável", "Prazo", "Risco", "Status"], [["JUR-026", "Contratual", "Assessoria jurídica", "22/08/2026", "Baixo", "Em análise"], ["JUR-021", "Marca", "Propriedade intelectual", "30/09/2026", "Médio", "Em andamento"], ["JUR-019", "Societário", "Diretoria", "15/10/2026", "Baixo", "Acompanhamento"]], "Novo assunto", ["Assuntos", "Processos", "Prazos", "Documentos"]),
  "/compliance-politicas": page("GOVERNANÇA", "Compliance e Políticas", "Obrigações, políticas corporativas, ocorrências e revisões.", ["Documento", "Categoria", "Versão", "Revisão", "Responsável", "Status"], [["Política de Segurança", "Segurança", "2.1", "10/12/2026", "Tecnologia", "Vigente"], ["Política de Privacidade", "LGPD", "3.0", "03/01/2027", "Jurídico", "Vigente"], ["Código de Conduta", "Governança", "1.4", "15/02/2027", "Diretoria", "Vigente"]], "Nova política", ["Políticas", "Obrigações", "Ocorrências", "Revisões"]),
  "/propriedade-intelectual": page("GOVERNANÇA", "Propriedade Intelectual", "Marcas, obras, registros e demais ativos intelectuais.", ["Ativo", "Tipo", "Registro", "Titular", "Validade", "Status"], [["LANDER SOLUTIONS", "Marca", "INPI 940112233", "Lander Solutions Ltda.", "2035", "Protocolado"], ["Music OS 360", "Marca", "INPI 940221144", "Lander Solutions Ltda.", "2035", "Em exame"], ["SONORIX", "Software", "Registro interno", "Lander Solutions Ltda.", "—", "Documentado"]], "Novo registro", ["Marcas", "Softwares", "Obras", "Prazos"]),
  "/acessos": page("GOVERNANÇA", "Acessos e Permissões", "Usuários, papéis, permissões e escopos de acesso.", ["Usuário", "Papel", "Escopo", "Último acesso", "MFA", "Status"], [["admin@lander.solutions", "Administrador", "Todas as unidades", "16/08 19:42", "Ativo", "Ativo"], ["financeiro@lander.solutions", "Financeiro", "Corporativo", "16/08 17:10", "Ativo", "Ativo"], ["suporte@lander.solutions", "Atendimento", "Produtos", "16/08 18:05", "Ativo", "Ativo"]], "Novo acesso", ["Usuários", "Papéis", "Permissões", "Escopos"]),
  "/auditoria": page("GOVERNANÇA", "Trilha de auditoria", "Registro de ações relevantes executadas dentro do sistema.", ["Data/hora", "Usuário", "Ação", "Módulo", "Registro", "Resultado"], [["16/08 19:41", "Administrador", "UPDATE", "Contratos", "CTR-2026-041", "Sucesso"], ["16/08 19:38", "Financeiro", "CREATE", "Transações", "TRX-8821", "Sucesso"], ["16/08 18:57", "Comercial", "UPDATE", "CRM", "LEAD-031", "Sucesso"]], "Exportar trilha", ["Eventos", "Alterações", "Acessos", "Falhas"]),
  "/relatorios": page("GESTÃO CORPORATIVA", "Relatórios", "Demonstrativos gerenciais e indicadores consolidados da operação.", ["Relatório", "Escopo", "Competência", "Última geração", "Status"], [["DRE gerencial", "Todas as unidades", "08/2026", "16/08 18:30", "Disponível"], ["Resultado por unidade", "Produtos / SaaS", "08/2026", "16/08 18:31", "Disponível"], ["Repasses pendentes", "Participações", "08/2026", "16/08 18:32", "Disponível"], ["Fluxo de caixa", "Corporativo", "08/2026", "16/08 18:33", "Disponível"]], "Gerar relatório", ["Gerenciais", "Financeiros", "Operacionais", "Agendados"]),
  "/integracoes": page("GESTÃO CORPORATIVA", "Integrações", "Conectores que alimentam a operação corporativa.", ["Integração", "Categoria", "Última sincronização", "Registros", "Status"], [["Supabase", "Dados", "16/08 19:40", "12.480", "Conectado"], ["Stripe", "Pagamentos", "16/08 19:36", "1.842", "Conectado"], ["Resend", "E-mail", "16/08 19:32", "428", "Conectado"]], "Configurar integração"),
  "/configuracoes/integracoes": page("CONFIGURAÇÕES", "Configurações de Integrações", "Credenciais, escopos e parâmetros técnicos dos conectores.", ["Conector", "Ambiente", "Escopo", "Validação", "Status"], [["Supabase", "Produção", "Banco/Auth", "16/08/2026", "Válido"], ["Stripe", "Produção", "Pagamentos", "16/08/2026", "Válido"], ["Resend", "Produção", "E-mail", "16/08/2026", "Válido"]], "Nova configuração", ["Conectores", "Credenciais", "Webhooks"]),
  "/configuracoes-servicos-leads": page("CONFIGURAÇÕES", "Serviços de Leads", "Serviços disponíveis para seleção e qualificação comercial.", ["Serviço", "Unidade", "Categoria", "Ordem", "Status"], [["Desenvolvimento SaaS", "Corporativo", "Tecnologia", "1", "Ativo"], ["Music OS 360", "Music OS 360", "SaaS", "2", "Ativo"], ["Consultoria estratégica", "Corporativo", "Consultoria", "3", "Ativo"]], "Novo serviço"),
  "/configuracoes-templates-contratos": page("CONFIGURAÇÕES", "Templates de Contratos", "Modelos padronizados utilizados na criação dos contratos.", ["Template", "Categoria", "Versão", "Última alteração", "Status"], [["Prestação de Serviços", "Serviços", "v4", "12/08/2026", "Ativo"], ["Licença SaaS", "SaaS", "v3", "01/08/2026", "Ativo"], ["Parceria comercial", "Parcerias", "v2", "21/07/2026", "Ativo"]], "Novo template", ["Templates", "Categorias", "Histórico"]),
  "/configuracoes-variaveis-contratos": page("CONFIGURAÇÕES", "Variáveis de Contratos", "Biblioteca de variáveis reutilizáveis nos templates contratuais.", ["Variável", "Rótulo", "Origem", "Obrigatória", "Status"], [["{{cliente.razao_social}}", "Razão social", "Cliente", "Sim", "Ativa"], ["{{contrato.valor}}", "Valor do contrato", "Contrato", "Sim", "Ativa"], ["{{empresa.cnpj}}", "CNPJ da Lander", "Empresa", "Sim", "Ativa"]], "Nova variável"),
};

const CRM_CONTACTS = [["Orbita Comércio Ltda.", "Cliente", "Pessoa Jurídica", "financeiro@orbita.com.br", "Music OS 360", "Ativo"], ["Nexo Produções", "Cliente", "Pessoa Jurídica", "contato@nexoproducoes.com", "Vivendo da Música", "Ativo"], ["Marina Carvalho", "Contato", "Pessoa Física", "marina@auroradigital.com", "Corporativo", "Ativo"], ["Cloud Partners Brasil", "Parceiro", "Pessoa Jurídica", "parcerias@cloudpartners.com", "Corporativo", "Ativo"]];
const CRM_LEADS = [["Aurora Digital", "Pessoa Jurídica", "contato@auroradigital.com", "Desenvolvimento SaaS", "Site", "Qualificado"], ["Estúdio Horizonte", "Pessoa Jurídica", "studio@horizonte.com", "Music OS 360", "Indicação", "Novo"], ["Lucas Mendes", "Pessoa Física", "lucas@email.com", "Consultoria", "WhatsApp", "Contato pendente"]];

export function FrontendPreviewPage() {
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  if (pathname === "/crm" || pathname === "/clientes") return <CrmPreview />;
  const normalizedPath = pathname.startsWith("/unidades/") ? "/unidades" : pathname;
  return <BusinessPage key={normalizedPath} definition={PAGES[normalizedPath] ?? page("LANDER SOLUTIONS", "Página", "Conteúdo operacional da Lander Solutions.", ["Registro", "Categoria", "Responsável", "Status"], [["Registro de exemplo", "Operacional", "Equipe Lander", "Ativo"]], "Novo registro")} />;
}

function BusinessPage({ definition }: { definition: PageDefinition }) {
  const [rows, setRows] = useState(() => definition.rows.map((row) => [...row]));
  const [query, setQuery] = useState("");
  const [activeTab, setActiveTab] = useState(definition.tabs?.[0] ?? "Registros");
  const [filterOpen, setFilterOpen] = useState(false);
  const [statusOnly, setStatusOnly] = useState(false);
  const [compact, setCompact] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [editor, setEditor] = useState<EditorState>(null);

  const visibleRows = useMemo(() => rows.filter((row) => {
    const matchesQuery = row.join(" ").toLowerCase().includes(query.trim().toLowerCase());
    const matchesStatus = !statusOnly || !["inativo", "fechado", "arquivado"].includes((row.at(-1) ?? "").toLowerCase());
    return matchesQuery && matchesStatus;
  }), [query, rows, statusOnly]);

  const saveRecord = (values: string[]) => {
    if (editor?.mode === "edit" && editor.index !== undefined) setRows((current) => current.map((row, index) => index === editor.index ? values : row));
    if (editor?.mode === "create") setRows((current) => [...current, values]);
    setEditor(null);
  };
  const exportCsv = () => {
    const csv = [definition.columns, ...visibleRows].map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${definition.title.toLowerCase().replaceAll(" ", "-")}.csv`; anchor.click(); URL.revokeObjectURL(url);
    setNotice("Arquivo CSV preparado para download.");
  };

  return <div className="space-y-5">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
      <div className="max-w-3xl"><p className="label-caps">{definition.eyebrow}</p><h1 className="mt-1 text-2xl font-semibold md:text-3xl">{definition.title}</h1><p className="mt-1 text-sm leading-6 text-muted-foreground">{definition.description}</p></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportCsv}><Download className="h-4 w-4" /> Exportar</Button><Button onClick={() => setEditor({ mode: "create" })}><Plus className="h-4 w-4" /> {definition.primaryAction}</Button></div>
    </div>
    {definition.tabs && <nav className="flex gap-1 overflow-x-auto rounded-lg border bg-card p-1">{definition.tabs.map((tab) => <Button key={tab} size="sm" variant={activeTab === tab ? "default" : "ghost"} onClick={() => { setActiveTab(tab); setNotice(`Seção ${tab} selecionada.`); }}>{tab}</Button>)}</nav>}
    <KpiGrid items={definition.kpis} />
    {notice && <div className="flex items-center justify-between rounded-lg border border-primary/30 bg-primary/5 px-4 py-3 text-sm"><span>{notice}</span><Button size="sm" variant="ghost" onClick={() => setNotice(null)}>Fechar</Button></div>}
    <div className="grid gap-4 2xl:grid-cols-[minmax(0,1fr)_320px]">
      <section className="min-w-0 overflow-hidden rounded-lg border bg-card shadow-sm">
        <div className="flex flex-col gap-3 border-b p-4 lg:flex-row lg:items-center lg:justify-between">
          <div><h2 className="font-semibold">{activeTab}</h2><p className="text-sm text-muted-foreground">{visibleRows.length} registro(s) nesta visão.</p></div>
          <div className="flex flex-col gap-2 sm:flex-row"><div className="relative sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar nesta página" className="pl-9" /></div><Button variant={filterOpen ? "default" : "outline"} size="sm" onClick={() => setFilterOpen((value) => !value)}><Filter className="h-4 w-4" /> Filtros</Button><Button variant="outline" size="sm" onClick={() => setCompact((value) => !value)}><SlidersHorizontal className="h-4 w-4" /> {compact ? "Confortável" : "Compacta"}</Button></div>
        </div>
        {filterOpen && <div className="flex flex-wrap items-center gap-3 border-b bg-muted/20 px-4 py-3 text-sm"><Button size="sm" variant={statusOnly ? "default" : "outline"} onClick={() => setStatusOnly((value) => !value)}>Somente ativos</Button><Button size="sm" variant="ghost" onClick={() => { setQuery(""); setStatusOnly(false); }}>Limpar filtros</Button></div>}
        <DataTable columns={definition.columns} rows={visibleRows} compact={compact} onView={(row) => setEditor({ mode: "view", row })} onEdit={(row) => setEditor({ mode: "edit", index: rows.indexOf(row), row })} onArchive={(row) => { setRows((current) => current.filter((item) => item !== row)); setNotice(`${row[0]} arquivado na demonstração.`); }} />
        <div className="flex items-center justify-between border-t px-4 py-3 text-xs text-muted-foreground"><span>Mostrando {visibleRows.length} de {rows.length}</span><Button size="sm" variant="outline" onClick={() => setNotice("Paginação pronta para expansão quando houver mais registros.")}>Mais registros</Button></div>
      </section>
      <aside className="space-y-4"><section className="rounded-lg border bg-card p-4 shadow-sm"><h2 className="font-semibold">Resumo operacional</h2><div className="mt-3 space-y-2">{definition.summary.map((item) => <button key={item} type="button" onClick={() => setNotice(item)} className="w-full rounded-md border p-3 text-left text-sm transition hover:bg-muted/50">{item}</button>)}</div></section><section className="rounded-lg border bg-card p-4 shadow-sm"><h2 className="font-semibold">Ações rápidas</h2><div className="mt-3 grid gap-2"><Button variant="outline" onClick={() => setEditor({ mode: "create" })}><Plus className="h-4 w-4" /> Novo registro</Button><Button variant="outline" onClick={exportCsv}><Download className="h-4 w-4" /> Exportar visão</Button></div></section></aside>
    </div>
    <RecordDialog state={editor} title={definition.title} columns={definition.columns} onClose={() => setEditor(null)} onSave={saveRecord} />
  </div>;
}

function CrmPreview() {
  const [tab, setTab] = useState<"contacts" | "leads">("contacts");
  const [contacts, setContacts] = useState(() => CRM_CONTACTS.map((row) => [...row]));
  const [leads, setLeads] = useState(() => CRM_LEADS.map((row) => [...row]));
  const [query, setQuery] = useState(""); const [filterOpen, setFilterOpen] = useState(false); const [editor, setEditor] = useState<EditorState>(null); const [notice, setNotice] = useState<string | null>(null);
  const rows = tab === "contacts" ? contacts : leads;
  const columns = tab === "contacts" ? ["Nome", "Relacionamento", "Tipo", "Contato", "Unidade", "Status"] : ["Lead", "Tipo", "Contato", "Interesse", "Origem", "Status"];
  const visibleRows = rows.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase()));
  const kpis: Kpi[] = tab === "contacts" ? [{ label: "Contatos / clientes", value: "48", hint: "31 clientes ativos" }, { label: "Clientes ativos", value: "31", hint: "+4 no mês" }, { label: "Parceiros", value: "7" }, { label: "Outros contatos", value: "10" }] : [{ label: "Total de leads", value: "23" }, { label: "Novos", value: "8" }, { label: "Qualificados", value: "6" }, { label: "Convertidos no mês", value: "9" }];
  const setRows = (next: string[][]) => tab === "contacts" ? setContacts(next) : setLeads(next);
  const save = (values: string[]) => { if (editor?.mode === "create") setRows([...rows, values]); else if (editor?.mode === "edit" && editor.index !== undefined) setRows(rows.map((row, index) => index === editor.index ? values : row)); setEditor(null); };
  const exportCsv = () => { const csv = [columns, ...visibleRows].map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `crm-${tab}.csv`; anchor.click(); URL.revokeObjectURL(url); setNotice("CRM exportado em CSV."); };
  return <div className="space-y-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="label-caps">COMERCIAL</p><h1 className="mt-1 text-3xl font-semibold">CRM</h1><p className="mt-1 text-sm text-muted-foreground">Centralize contatos, clientes e leads e acompanhe todo o relacionamento comercial.</p></div><div className="flex gap-2"><Button variant="outline" onClick={exportCsv}><Download className="h-4 w-4" /> Exportar CRM</Button><Button onClick={() => setEditor({ mode: "create" })}><Plus className="h-4 w-4" /> {tab === "contacts" ? "Novo Contato / Cliente" : "Novo Lead"}</Button></div></div><nav className="flex gap-1 rounded-lg border bg-card p-1"><Button size="sm" variant={tab === "contacts" ? "default" : "ghost"} onClick={() => { setTab("contacts"); setQuery(""); }}>Contatos / Clientes</Button><Button size="sm" variant={tab === "leads" ? "default" : "ghost"} onClick={() => { setTab("leads"); setQuery(""); }}>Leads</Button></nav><KpiGrid items={kpis} />{notice && <div className="flex items-center justify-between rounded-lg border bg-primary/5 px-4 py-3 text-sm"><span>{notice}</span><Button size="sm" variant="ghost" onClick={() => setNotice(null)}>Fechar</Button></div>}<section className="overflow-hidden rounded-lg border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b p-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold">{tab === "contacts" ? "Contatos / Clientes" : "Leads"}</h2><p className="text-sm text-muted-foreground">{tab === "contacts" ? "Pessoas e empresas com relacionamento ativo com a Lander Solutions." : "Oportunidades comerciais ainda não convertidas."}</p></div><div className="flex gap-2"><div className="relative w-80 max-w-full"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar" className="pl-9" /></div><Button variant={filterOpen ? "default" : "outline"} size="sm" onClick={() => setFilterOpen((value) => !value)}><Filter className="h-4 w-4" /> Filtros</Button></div></div>{filterOpen && <div className="border-b bg-muted/20 px-4 py-3"><Button size="sm" variant="outline" onClick={() => setQuery("")}>Limpar busca</Button></div>}<DataTable columns={columns} rows={visibleRows} compact={false} onView={(row) => setEditor({ mode: "view", row })} onEdit={(row) => setEditor({ mode: "edit", index: rows.indexOf(row), row })} onArchive={(row) => { setRows(rows.filter((item) => item !== row)); setNotice(`${row[0]} arquivado.`); }} /></section><RecordDialog state={editor} title={tab === "contacts" ? "Contato / Cliente" : "Lead"} columns={columns} onClose={() => setEditor(null)} onSave={save} /></div>;
}

function KpiGrid({ items }: { items: Kpi[] }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <div key={item.label} className="rounded-lg border bg-card p-4 shadow-sm"><p className="text-xs font-medium text-muted-foreground">{item.label}</p><p className="mt-2 text-2xl font-semibold">{item.value}</p>{item.hint && <p className="mt-1 text-xs text-muted-foreground">{item.hint}</p>}</div>)}</div>; }

function DataTable({ columns, rows, compact, onView, onEdit, onArchive }: { columns: string[]; rows: string[][]; compact: boolean; onView: (row: string[]) => void; onEdit: (row: string[]) => void; onArchive: (row: string[]) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="bg-muted/50"><tr>{columns.map((column) => <th key={column} className="whitespace-nowrap px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">{column}</th>)}<th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wide text-muted-foreground">Ações</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`} className="border-t hover:bg-muted/30">{row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`} className={`whitespace-nowrap px-4 ${compact ? "py-2" : "py-3"}`}>{cellIndex === row.length - 1 ? <StatusPill status={cell} /> : cell}</td>)}<td className="px-4 py-2 text-right"><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label={`Ações de ${row[0]}`}><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => onView(row)}><Eye className="h-4 w-4" /> Ver</DropdownMenuItem><DropdownMenuItem onSelect={() => onEdit(row)}><Pencil className="h-4 w-4" /> Editar</DropdownMenuItem><DropdownMenuItem onSelect={() => onArchive(row)}><Trash2 className="h-4 w-4" /> Arquivar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></td></tr>)}{rows.length === 0 && <tr><td colSpan={columns.length + 1} className="px-4 py-10 text-center text-muted-foreground">Nenhum registro encontrado.</td></tr>}</tbody></table></div>; }

function RecordDialog({ state, title, columns, onClose, onSave }: { state: EditorState; title: string; columns: string[]; onClose: () => void; onSave: (values: string[]) => void }) {
  const [values, setValues] = useState<string[]>([]);
  const source = state?.row ?? columns.map(() => "");
  const current = values.length === columns.length ? values : source;
  const editable = state?.mode !== "view";
  return <Dialog open={Boolean(state)} onOpenChange={(open) => { if (!open) { setValues([]); onClose(); } }}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{state?.mode === "create" ? `Novo ${title}` : state?.mode === "edit" ? `Editar ${title}` : `Visualizar ${title}`}</DialogTitle><DialogDescription>{editable ? "Preencha os dados e salve para atualizar a demonstração do frontend." : "Detalhes do registro selecionado."}</DialogDescription></DialogHeader><div className="grid gap-4 py-2 sm:grid-cols-2">{columns.map((column, index) => <div key={column} className="space-y-1.5"><Label>{column}</Label><Input value={current[index] ?? ""} disabled={!editable} onChange={(event) => { const next = [...current]; next[index] = event.target.value; setValues(next); }} placeholder={`Informe ${column.toLowerCase()}`} /></div>)}</div><DialogFooter><Button variant="outline" onClick={() => { setValues([]); onClose(); }}>{editable ? "Cancelar" : "Fechar"}</Button>{editable && <Button onClick={() => { onSave(current); setValues([]); }}>Salvar</Button>}</DialogFooter></DialogContent></Dialog>;
}
